export const ADD_ARTICLE = "ADD_ARTICLE";
export const LOAD_ARTICLES_SUCCESS = "LOAD_ARTICLES_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_USER_FAILURE = "AUTH_USER_FAILURE";
export const USER_SIGN_OUT = "USER_SIGN_OUT";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
